version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
    - /bin/bash
    - -c
    - |
      python manage.py migrate 
      python manage.py runserver 0.0.0.0:8000

    image: django-nextjs-example
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    env_file:
      - ./.envs/.myenvs
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.myenvs